// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApp.Library.DataBase;

namespace TestApp.Library.Migrations
{
    [DbContext(typeof(FabricContext))]
    partial class FabricContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestApp.Library.DataBase.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryCode")
                        .IsRequired();

                    b.Property<string>("CategoryName")
                        .IsRequired();

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TestApp.Library.DataBase.Fabric", b =>
                {
                    b.Property<int>("FabricId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FabricCode")
                        .IsRequired();

                    b.Property<string>("FabricName")
                        .IsRequired();

                    b.HasKey("FabricId");

                    b.HasIndex("FabricCode")
                        .IsUnique();

                    b.ToTable("Fabrics");
                });

            modelBuilder.Entity("TestApp.Library.DataBase.Identifier", b =>
                {
                    b.Property<int>("IdentifierId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<int>("FabricId");

                    b.Property<int>("IdentifierNumber");

                    b.HasKey("IdentifierId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FabricId", "CategoryId", "IdentifierId")
                        .IsUnique();

                    b.ToTable("Identifiers");
                });

            modelBuilder.Entity("TestApp.Library.DataBase.Identifier", b =>
                {
                    b.HasOne("TestApp.Library.DataBase.Category", "Category")
                        .WithMany("Identifiers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TestApp.Library.DataBase.Fabric", "Fabric")
                        .WithMany("Identifiers")
                        .HasForeignKey("FabricId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
